name: demo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel # required for jupyter notebook in VS Code
  - pip:  # if you need more packages installed from pip 
      - azure-ai-documentintelligence==1.0.0b2
      - python-dotenv==1.0.1
#   - pip:
#     - foo